"""update models

Revision ID: 261c739576cd
Revises: 67c7fe876f09
Create Date: 2017-05-31 13:26:42.466767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '261c739576cd'
down_revision = '67c7fe876f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('colors', 'color',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('colors', 'mood',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('date_color', 'color_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('date_color', 'date_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dates', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_color', 'color_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_color', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_date', 'date_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_date', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_date', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_date', 'date_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_color', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_color', 'color_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dates', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('date_color', 'date_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('date_color', 'color_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('colors', 'mood',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('colors', 'color',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
