"""edit date model

Revision ID: 84260a442183
Revises: 261c739576cd
Create Date: 2017-06-01 11:11:33.665682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84260a442183'
down_revision = '261c739576cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dates', sa.Column('mood', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dates', 'mood')
    # ### end Alembic commands ###
