"""major edit to models

Revision ID: b341027c20c6
Revises: 84260a442183
Create Date: 2017-06-01 13:33:09.829353

"""
from alembic import op
import sqlalchemy as sa
from colour import Color
from sqlalchemy_utils import ColorType


# revision identifiers, used by Alembic.
revision = 'b341027c20c6'
down_revision = '84260a442183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_color')
    op.drop_table('user_date')
    op.drop_table('date_color')
    op.drop_table('colors')
    op.add_column('dates', sa.Column('color', ColorType, nullable=True))
    op.add_column('dates', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dates', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dates', type_='foreignkey')
    op.drop_column('dates', 'user_id')
    op.drop_column('dates', 'color')
    op.create_table('date_color',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('color_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name='date_color_color_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['date_id'], ['dates.id'], name='date_color_date_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='date_color_pkey')
    )
    op.create_table('user_date',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['dates.id'], name='user_date_date_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_date_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_date_pkey')
    )
    op.create_table('colors',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('colors_id_seq'::regclass)"), nullable=False),
    sa.Column('color', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mood', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='colors_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_color',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('color_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name='user_color_color_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_color_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_color_pkey')
    )
    # ### end Alembic commands ###
